# Site settings
title: NEMの説明書
url: "http://http://nemmanual.net/" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
exclude: ["vendor", "Gemfile", "Gemfile.lock", "CNAME", "README.md", ".ruby-version"]

collections:
  pages:
    output: true
    permalink: /:title.html
